### ISSUE TITLE
Fix size of japanese placeholder text

### ISSUE THREAD

**Issue by jj-tetraquark** [jonnydark/wanikani-burn#15]
It's too large

**Comment by jj-tetraquark** [comment]
This might be a linux-only issue.

**Comment by DJTB** [comment]
Can you screenshot this?
I'm on linux w/ chrome and it looks normal enough.
If anything, the meaning/reading text is oddly large.

![image](https://user-images.githubusercontent.com/5353151/27825503-11261668-60b0-11e7-953b-2d8c26855b70.png)

**Comment by jj-tetraquark** [comment]
Yeah I'm on linux/chrome as well. Given that I opened this a year ago and haven't done anything about it probably means I don't actually care and I'm not even sure what I was referring to anymore.

- Gonna call it a WontFix
