### ISSUE TITLE
Poor resolution resize

### ISSUE THREAD

**Issue by patarapolw** [jonnydark/wanikani-burn#16]
when I resize the window, the resolution is poor.

http://imageshack.com/a/img922/4093/YnkSPF.png

**Comment by jj-tetraquark** [comment]
This is a bug in Safari in how it handles scaling. I think I found a workaround but I am unable to test this as I don't have a mac. I'll put the potential fix in to the next release and I'll let you know when that's released and you can tell me if it fixed the issue or not :)

**Comment by jj-tetraquark** [comment]
Hey @patarapolw , a fix for this should now be master. If you do an update in greasemonkey it should fetch it. Let me know if this fixes the issue for you or not :)

**Comment by jj-tetraquark** [comment]
@patarapolw I'm marking this issue as closed. If it's still broken for you, please reopen this bug and I'll try and fix it.
