### ISSUE TITLE
Allow auto-correction of "n" to "ん" at end of input for Reading quiz 

### ISSUE THREAD

**Issue by gremlinn** [jonnydark/wanikani-burn#19]
Minor enhancement request, but it'd be great (to speed up quizzes) if, when processing the input for a Reading quiz, any input string ending in "n" would have this automatically replaced this with kana "ん" (as WaniKani does in reviews).
![image](https://cloud.githubusercontent.com/assets/26725322/24378464/a2a21466-1308-11e7-8d7e-76746fd9de94.png)

**Comment by DJTB** [comment]
From kaniwani
```
function addTerminalN(str = '') {
  return /n/i.test(str.slice(-1)) ? `${str.slice(0, -1)}ん` : str;
}
```
:)

**Comment by jj-tetraquark** [comment]
Yeah that'd do it :) If you want to submit a pull request I'll happily merge it in.
