### ISSUE TITLE
Dashboard level fields are full width

### ISSUE THREAD

**Issue by RayderBlitz** [jonnydark/wanikani-burn#6]
As I noticed a little while ago, when the script is active the popups when hovering over the different level-fields on the dashboard are resized to - from what I see - the window's width.

![unbenannt](https://cloud.githubusercontent.com/assets/19712823/15881299/25f62a60-2d35-11e6-9111-187f572ad620.PNG)

**Comment by jj-tetraquark** [comment]
This is now fixed as of commit 39cfe89 
Version 2.1.1 should be available on greasyfork with this fix
